services:
  web:
    image: wordline/psp-integration-web-prod
    build:
      dockerfile: ./Dockerfile.web
    ports:
      - 3000:3000
    volumes:
      - web_data:/app
    networks:
      - redisnet
      - dbnet
    environment:
      - CLIENT_ID=change_app_client_id
      - CLIENT_SECRET=change_app_secret
      - JWT_KEY=change_secret
      - DOMAIN=change_domain
      - REDIS_HOST=redis
      - MYSQL_HOST=db
      - MYSQL_USER=pspapp
      - MYSQL_PASSWORD=pspapp
      - AUTH_CALLBACK=https://${DOMAIN}/api/auth
      - SERVER_DOMAIN=https://${DOMAIN}
      - ENVIRONMENT=bigcommerce.com
      - LOGIN_URL=login.${ENVIRONMENT}
      - API_URL=api.${ENVIRONMENT}
      - DATABASE_URL="mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:3306/wordline-psp-integration"
      - CORS_ALLOWED_DOMAIN="*"
  cron:
    image: wordline/psp-integration-cron-prod
    build:
      dockerfile: ./Dockerfile.cron
    volumes:
      - cron_data:/app
    networks:
      - redisnet
      - dbnet
    environment:
      - CLIENT_ID=change_app_client_id
      - CLIENT_SECRET=change_app_secret
      - JWT_KEY=change_secret
      - REDIS_HOST=redis
      - MYSQL_HOST=db
      - MYSQL_USER=pspapp
      - MYSQL_PASSWORD=pspapp
      - ENVIRONMENT=bigcommerce.com
      - LOGIN_URL=login.${ENVIRONMENT}
      - API_URL=api.${ENVIRONMENT}
      - DATABASE_URL="mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:3306/ignite-psp-integration"
  redis:
    image: redis:alpine
    restart: always
    networks:
      - redisnet
    expose:
      - 6379
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dbnet
    environment:
      - MYSQL_USER=pspapp
      - MYSQL_ROOT_PASSWORD=pspapp
      - MYSQL_PASSWORD=pspapp
    expose:
      - 3306
volumes:
  db_data:
  web_data:
  cron_data:
networks:
  dbnet:
  redisnet:
