services:
  web:
    image: worldline/ctintegration-web-prod
    restart: "no"
    build:
      context: .
      dockerfile: ./Dockerfile.web
    ports:
      - 3000:3000
    networks:
      - redisnet
      - dbnet
    env_file:
      - .env
  mc:
    image: worldline/ctintegration-mc-prod
    restart: "no"
    build:
      context: .
      dockerfile: ./Dockerfile.mc
    ports:
      - 80:80
    networks:
      - redisnet
    env_file:
      - compose.env
  cron:
    image: worldline/ctintegration-cron-prod
    restart: "no"
    build:
      context: .
      dockerfile: ./Dockerfile.cron
    networks:
      - redisnet
      - dbnet
    env_file:
      - .env
  redis:
    image: redis:alpine
    restart: "no"
    networks:
      - redisnet
    expose:
      - 6379
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: "no"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dbnet
    env_file:
      - compose.env
    expose:
      - 3306
volumes:
  db_data:
networks:
  dbnet:
  redisnet:
