version: "3"

services:
  web:
    healthcheck:
      test: 'curl --fail http://localhost:3000/api/health'
      interval: 60s
      timeout: 5s
      retries: 30
  mc:
    healthcheck:
      test: 'curl --fail http://localhost:3001'
      interval: 60s
      timeout: 5s
      retries: 30

  db:
    healthcheck:
      test: 'mysqladmin ping -h localhost -u root -pwe83up'
      interval: 60s
      timeout: 5s
      retries: 30

  redis:
    healthcheck:
      test: 'redis-cli ping || exit 1'
      interval: 60s
      timeout: 5s
      retries: 30

