FROM node:18-alpine as dependencies

RUN apk update && apk upgrade

WORKDIR /app
RUN mkdir app ct db psp util web
COPY app/package*.json ./app/
COPY ct/package*.json ./ct/
COPY db/package*.json ./db/
COPY psp/package*.json ./psp/
COPY util/package*.json ./util/
COPY web/package*.json ./web/
COPY package*.json ./

RUN npm ci

FROM node:18-alpine as build

RUN apk update && apk upgrade

WORKDIR /app
COPY --from=dependencies /app/app/node_modules ./app/node_modules
COPY --from=dependencies /app/ct/node_modules ./ct/node_modules
COPY --from=dependencies /app/db/node_modules ./db/node_modules
COPY --from=dependencies /app/psp/node_modules ./psp/node_modules
COPY --from=dependencies /app/util/node_modules ./util/node_modules
COPY --from=dependencies /app/web/node_modules ./web/node_modules
COPY --from=dependencies /app/node_modules ./node_modules
COPY --from=dependencies /app/package.json ./package.json

COPY ./app ./app
COPY ./ct ./ct
COPY ./db ./db
COPY ./psp ./psp
COPY ./util ./util
COPY ./web ./web

#generate prisma.
RUN npm run prisma:generate

RUN npm run build

FROM node:18-alpine as deploy

ENV NODE_ENV production

RUN apk update && apk upgrade

WORKDIR /app
RUN mkdir app ct db psp util web

COPY --from=build /app/app/dist ./app/dist
COPY ./app/package*.json ./app/

COPY --from=build /app/ct/dist ./ct/dist
COPY ./ct/package*.json ./ct/

COPY --from=build /app/db/dist ./db/dist
COPY ./db/package*.json ./db/
#needed for prisma migration.
COPY db/prisma ./db/prisma

COPY --from=build /app/psp/dist ./psp/dist
COPY ./psp/package*.json ./psp/

COPY --from=build /app/util/dist ./util/dist
COPY ./util/package*.json ./util/

COPY --from=build /app/web/package*.json ./web/
COPY --from=build /app/web/dist ./web/dist
COPY ./migrate-db-and-start.sh ./migrate-db-and-start.sh

COPY ./package*.json ./

RUN npm ci --ignore-scripts

EXPOSE 3000
CMD ["./migrate-db-and-start.sh"]