FROM node:18-alpine as server

RUN apk update && apk upgrade
RUN apk --no-cache add git

WORKDIR /app
RUN mkdir app ct db psp util web
COPY app/package*.json ./app
COPY ct/package*.json ./ct
COPY db/package*.json ./db
COPY psp/package*.json ./psp
COPY util/package*.json ./util
COPY web/package*.json ./web
COPY cron/package*.json ./cron
RUN npm ci
COPY ./app ./app
COPY ./ct ./ct
COPY ./db ./db
COPY ./psp ./psp
COPY ./util ./util
COPY ./web ./web
COPY ./cron ./cron

RUN npm run prisma:generate

ENV NODE_ENV development

EXPOSE 3000
CMD ["npm", "run", "dev"]