FROM node:18-alpine as dependencies

RUN apk update && apk upgrade
RUN apk add --no-cache git

WORKDIR /app
RUN mkdir app ct db mock psp util web
COPY app/package*.json ./app
COPY ct/package*.json ./ct
COPY db/package*.json ./db
COPY mock/package*.json ./mock
COPY psp/package*.json ./psp
COPY util/package*.json ./util
COPY web/package*.json ./web
WORKDIR /app/web
RUN npm run install:ci:all

FROM node:18-alpine as build

RUN apk update && apk upgrade
RUN apk add --no-cache git

WORKDIR /app

COPY --from=dependencies /app/app/node_modules ./app/node_modules
COPY --from=dependencies /app/ct/node_modules ./ct/node_modules
COPY --from=dependencies /app/db/node_modules ./db/node_modules
COPY --from=dependencies /app/mock/node_modules ./mock/node_modules
COPY --from=dependencies /app/psp/node_modules ./psp/node_modules
COPY --from=dependencies /app/util/node_modules ./util/node_modules
COPY --from=dependencies /app/web/node_modules ./web/node_modules
COPY ./app ./app
COPY ./ct ./ct
COPY ./db ./db
COPY ./mock ./mock
COPY ./psp ./psp
COPY ./util ./util
COPY ./web ./web

#generate prisma.
WORKDIR /app/web
RUN npm run prisma:generate:all

RUN npm run build:all

FROM node:18-alpine as deploy

RUN apk update && apk upgrade
RUN apk add --no-cache git

WORKDIR /app
RUN mkdir app ct db mock psp util web
ENV NODE_ENV production

COPY --from=build /app/app/dist ./app/dist
COPY --from=build /app/app/node_modules ./app/node_modules
COPY --from=build /app/app/package.json ./app/package.json

COPY --from=build /app/ct/dist ./ct/dist
COPY --from=build /app/ct/node_modules ./ct/node_modules
COPY --from=build /app/ct/package.json ./ct/package.json

COPY --from=build /app/db/dist ./db/dist
COPY --from=build /app/db/node_modules ./db/node_modules
COPY --from=build /app/db/package.json ./db/package.json

COPY --from=build /app/mock/dist ./mock/dist
COPY --from=build /app/mock/node_modules ./mock/node_modules
COPY --from=build /app/mock/package.json ./mock/package.json

COPY --from=build /app/psp/dist ./psp/dist
COPY --from=build /app/psp/node_modules ./psp/node_modules
COPY --from=build /app/psp/package.json ./psp/package.json

COPY --from=build /app/util/dist ./util/dist
COPY --from=build /app/util/node_modules ./util/node_modules
COPY --from=build /app/util/package.json ./util/package.json

COPY --from=build /app/web/node_modules ./web/node_modules
COPY --from=build /app/web/public ./web/public
COPY --from=build /app/web/package.json ./web/package.json
COPY --from=build /app/web/build ./web/build

EXPOSE 3000
WORKDIR /app/web
CMD ["npm", "run", "start"]