FROM node:18-alpine as dependencies

RUN apk update && apk upgrade
RUN apk add --no-cache git

WORKDIR /app
COPY app/package*.json .
RUN mkdir app ct db psp util web
COPY app/package*.json ./app
COPY ct/package*.json ./ct
COPY db/package*.json ./db
COPY psp/package*.json ./psp
COPY util/package*.json ./util
COPY web/package*.json ./web
COPY package*.json .
RUN npm ci

FROM node:18-alpine as build

RUN apk update && apk upgrade
RUN apk add --no-cache git

WORKDIR /app

COPY --from=dependencies /app/app/node_modules ./app/node_modules
COPY --from=dependencies /app/ct/node_modules ./ct/node_modules
COPY --from=dependencies /app/db/node_modules ./db/node_modules
COPY --from=dependencies /app/psp/node_modules ./psp/node_modules
COPY --from=dependencies /app/util/node_modules ./util/node_modules
COPY --from=dependencies /app/web/node_modules ./web/node_modules
COPY --from=dependencies /app/node_modules ./node_modules
COPY ./app ./app
COPY ./ct ./ct
COPY ./db ./db
COPY ./psp ./psp
COPY ./util ./util
COPY ./web ./web

#generate prisma.
RUN npm run prisma:generate

RUN npm run build

FROM node:18-alpine as deploy

RUN apk update && apk upgrade
RUN apk add --no-cache git

WORKDIR /app
RUN mkdir app ct db psp util web
ENV NODE_ENV production

COPY --from=build /app/app/dist ./app/dist
COPY --from=build /app/app/node_modules ./app/node_modules
COPY --from=build /app/app/package.json ./app/package.json

COPY --from=build /app/ct/dist ./ct/dist
COPY --from=build /app/ct/node_modules ./ct/node_modules
COPY --from=build /app/ct/package.json ./ct/package.json

COPY --from=build /app/db/dist ./db/dist
COPY --from=build /app/db/node_modules ./db/node_modules
COPY --from=build /app/db/package.json ./db/package.json
#needed for prisma migration.
COPY db/prisma ./db/prisma

COPY --from=build /app/psp/dist ./psp/dist
COPY --from=build /app/psp/node_modules ./psp/node_modules
COPY --from=build /app/psp/package.json ./psp/package.json

COPY --from=build /app/util/dist ./util/dist
COPY --from=build /app/util/node_modules ./util/node_modules
COPY --from=build /app/util/package.json ./util/package.json

COPY --from=build /app/web/build ./web/dist
COPY --from=build /app/web/node_modules ./web/node_modules
COPY --from=build /app/web/package.json ./web/package.json
COPY ./web/migrate-db-and-start.sh ./web/migrate-db-and-start.sh

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json

WORKDIR /app/web
EXPOSE 3000
CMD ["./migrate-db-and-start.sh"]