FROM node:18-alpine AS dependencies

RUN apk update && apk upgrade

WORKDIR /app
RUN mkdir app ct db psp util cron
COPY app/package*.json ./app/
COPY ct/package*.json ./ct/
COPY db/package*.json ./db/
COPY psp/package*.json ./psp/
COPY util/package*.json ./util/
COPY cron/package*.json ./cron/
COPY package*.json ./

RUN npm ci --ignore-scripts

FROM node:18-alpine AS build

RUN apk update && apk upgrade

WORKDIR /app

RUN mkdir app ct db psp util cron
COPY --from=dependencies /app/app/node_modules ./app/node_modules
COPY --from=dependencies /app/ct/node_modules ./ct/node_modules
COPY --from=dependencies /app/db/node_modules ./db/node_modules
COPY --from=dependencies /app/psp/node_modules ./psp/node_modules
COPY --from=dependencies /app/util/node_modules ./util/node_modules
COPY --from=dependencies /app/cron/node_modules ./cron/node_modules
COPY --from=dependencies /app/node_modules ./node_modules
COPY --from=dependencies /app/package.json ./package.json

COPY ./app ./app
COPY ./ct ./ct
COPY ./db ./db
COPY ./psp ./psp
COPY ./util ./util
COPY ./cron ./cron

#generate prisma.
RUN npm run prisma:generate

RUN npm run build

FROM node:18-bullseye-slim AS deploy


RUN apt-get update && apt-get install -y nginx supervisor openssl && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN mkdir app ct db psp util web

COPY --from=build /app/app/dist ./app/dist
COPY ./app/package*.json ./app/

COPY --from=build /app/ct/dist ./ct/dist
COPY ./ct/package*.json ./ct/

COPY --from=build /app/db/dist ./db/dist
COPY ./db/package*.json ./db/
#needed for prisma generation.
COPY db/prisma ./db/prisma

COPY --from=build /app/psp/dist ./psp/dist
COPY ./psp/package*.json ./psp/

COPY --from=build /app/util/dist ./util/dist
COPY ./util/package*.json ./util/

COPY ./cron/package*.json ./cron/
COPY --from=build /app/cron/dist ./cron/dist

COPY ./package*.json ./

RUN npm ci --ignore-scripts

#generate prisma.
RUN npm run prisma:generate


RUN mkdir -p /etc/nginx/conf.d
COPY ./nginx.conf  /etc/nginx/sites-enabled/default
COPY ./supervisord.conf /etc/supervisord.conf

EXPOSE 80

CMD ["supervisord", "-c", "/etc/supervisord.conf"]